# Specify configuration of RBD depletion validation plots

resultsdir: results/rbd_absorptions
published_metadata: data/Crawford_SuppFile2.csv # this is Supplementary File 2 from Crawford et al. (2020)
sample_information: data/depletion_samples.csv # this is the mapping file with information specific to our study

elisa_input_files:
  - data/elisa_data_concatenated.csv

neut_input_files: # make sure it is in this format:
  data/201012_depletion_neuts.csv: 201012
  data/201026_depletion_neuts_updated.csv: 201026
  data/201030_depletion_neuts.csv: 201030
  data/201106_depletion_neuts.csv: 201106
  data/201111_depletion_neuts.csv: 201111
  data/pre-pandemic_fracinfect.csv: 201020

# the neutralization limit of detection is equal to the starting dilution
NT50_LOD: 20

neut_samples_ignore: # these are identified by manually looking through input files and finding samples that don't belong in final analysis
  - 13_d15_2xbeads
  - RegTest50
  - RegTest25

neut_ignore_dilutions: # cells were not added to "Row G" for all 23C samples (both timepoints, pre- and post-depletion).
  # so here I am indicating the samples and their dilutions
  # these should be key: value sample (befor being renamed): dilution (float)
  23C_d26: 0.000205761
  23C_d102: 0.000205761

neut_ignore_dates:
  24C_d32: 201026
  24C_d104: 201026
  1C_d26: 201026

# some samples are not relevant to this study. drop them from analysis.
elisa_samples_ignore:
  - 13_d15 (2x more beads used)
  - EZ-7A
  - 23_d45 # this was the one done with only one round of depletion, which was incomplete. The 2nd round of depletion was better; see below.
  - REGN10987_25ug/mL # decided to only show the 50ug/mL in final figure
  - REGN10987_5ug/mL # decided to only show the 50ug/mL in final figure

# some samples were run on multiple days but with the incorrect dilutions on some days to get comparable AUCs.
# Therefore we must drop those now
# these should be keyed sample: date (before renaming samples, as this will be done at the beginning of the notebook)
elisa_ignore_dates:
  2017-2018 serum pool: 201020
  1C_d26: 201021
  
# change names for some specific entries in ELISA files, before applying the "display names"
elisa_newnames:
  23_d45 (re-depleted): 23_d45

elisa_background_sample: pre-pandemic
