# the BioSample accession
biosample_accession: SAMN17185313

# name of CSV file listing barcode runs to uploade
barcode_runs: HAARVI_sera_barcode_runs.csv

# the following come from the SRA FTP upload instructions
ftp_username: subftp
ftp_account_folder: uploads/jbloom_fhcrc.org_IuMBgK44

# Meaningful name for this sample's FTP folder:
ftp_subfolder: HAARVI_sera_barcodes
